#pragma config(Sensor, in1,    potientm,       sensorPotentiometer)
#pragma config(Sensor, in2,    lightsensor,    sensorReflection)
#pragma config(Sensor, in3,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in4,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in5,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in6,    accel,          sensorAccelerometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  armDown,        sensorTouch)
#pragma config(Sensor, dgtl8,  sonarCM,        sensorSONAR_cm)
#pragma config(Sensor, dgtl10, rightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armGrab,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Verkefni 6 -                                             *|
|*                                      															  *|
|*			Drives on the line to the until it is near the ball, then 		                          *|
|*			picks up the ball, turns around, drives on the line to the basket and drop the ball       *|
|*																		                              *|
\*-----------------------------------------------------------------------------------------------4246-*/
#include "verkefni.c"


task main()
{
    while (true)
    {
			if (VexRT[Btn7D]){ startTask(verkefni2); }
			else if (VexRT[Btn7R]){ startTask(verkefni3); }
			else if (VexRT[Btn7U]){ startTask(verkefni4); }
			else if (VexRT[Btn7L]){ startTask(verkefni5); }
			else if (VexRT[Btn8D]){ startTask(verkefni6); }
			wait1Msec(1);
    }
}
