#pragma config(Sensor, in1,    potientm,       sensorPotentiometer)
#pragma config(Sensor, in2,    lightsensor,    sensorReflection)
#pragma config(Sensor, in3,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in4,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in5,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in6,    accel,          sensorAccelerometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  sonarCM,        sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  armDown,        sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armGrab,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/
#include "../robheaders/const.h"
#include "../robfuncs/funcs.c"

int forwardValue = 0;

void turnWithController(int *motorValue1, int *motorValue2, int turnValue)
{
		if (motorValue1 < -5)
		{
			motorValue1 += turnValue;
			writeDebugStream("%d", (int)motorValue1 * -1);
		}
		else if (motorValue1 > 5)
		{
			motorValue1 -= turnValue;
			writeDebugStream("%d", (int)motorValue1 * -1);
		}
		else
		{
			motorValue1 = (int*)turnValue;
			motorValue2 = (int*)(turnValue * -1);
			writeDebugStream("%d", (int)motorValue1 * -1);

		}
}

void updateControllerValues()
{
	forwardValue = vexRT[Ch3];
}

void move()
{
		int leftMotorValue = forwardValue;
		int rightMotorValue = forwardValue;
		if (vexRT[ch1] > 10)
		{
				turnWithController(&rightMotorValue, &leftMotorValue, abs(vexRT[ch1]));
		}
		else if (vexRT[ch1] < -10)
		{
			turnWithController(&leftMotorValue, &rightMotorValue, abs(vexRT[ch1]));
		}
		setMotors(leftMotorValue, rightMotorValue);
}

task main()
{
	wait10Msec(1000);
	while (true)
	{
		updateControllerValues();
		move();
	 //setMotors((int) vexRT[Ch2], (int) vexRT[Ch3]);
	}
}
