#pragma config(Sensor, in1,    potientm,       sensorPotentiometer)
#pragma config(Sensor, in2,    lightsensor,    sensorReflection)
#pragma config(Sensor, in3,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in4,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in5,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in6,    accel,          sensorAccelerometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  sonarCM,        sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  armDown,        sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armGrab,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/
const int DEFAULTPOWER = 127;
const int ROBOTDIAMETER = 38;
const int WHEELDIAMETER = 10;

int Msec(int sec)
{
	return sec / 1000;
}

void drive(int power = DEFAULTPOWER, int time = 3000)
{
	int timeRemaining = time;
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	while (timeRemaining > 0)
	{
		int leftEncoder = SensorValue[leftEncoder];
		int rightEncoder = SensorValue[rightEncoder];
		if (leftEncoder == rightEncoder)
		{
			motor[rightMotor] = power;
			motor[leftMotor]  = power;
		}
		else if (leftEncoder > rightEncoder)
		{
				motor[rightMotor] = power;
				motor[leftMotor]  = power * 0.7;
		}
		else if (rightEncoder < leftEncoder)
		{
				motor[rightMotor] = power * 0.7;
				motor[leftMotor]  = power;
		}
		wait1Msec(1);
		timeRemaining--;
	}
}

void driveDistance(int cm = 60, int power = DEFAULTPOWER)
{
	SensorValue[leftEncoder] = 0;
	SensorValue[rightEncoder] = 0;
	while ((SensorValue[leftEncoder] * -1) < (cm / WHEELDIAMETER * 360))
	{
		int leftEncoder = SensorValue[leftEncoder] * -1;
		int rightEncoder = SensorValue[rightEncoder] * -1;
		if (leftEncoder == rightEncoder)
		{
			motor[rightMotor] = power;
			motor[leftMotor]  = power;
		}
		else if (leftEncoder > rightEncoder)
		{
				motor[rightMotor] = power;
				motor[leftMotor]  = power * 0.7;
		}
		else if (rightEncoder < leftEncoder)
		{
				motor[rightMotor] = power * 0.7;
				motor[leftMotor]  = power;
		}
		wait1Msec(1);
	}
}

void reverse(int power = DEFAULTPOWER, int time = 3000)
{
		drive(power * -1, time);
}

void turnRight(int deg = 90)
{
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;
	motor[rightMotor] = 127;
	motor[leftMotor]  = 0;
	while (((SensorValue[rightEncoder] * -1) / 360 * WHEELDIAMETER) < (deg / 360 * ROBOTDIAMETER))
	{
			wait1Msec(100);
	}
}

void turnLeft(int deg = 90)
{
	motor[rightMotor] = 0;
	motor[leftMotor]  = 127;
	wait1Msec(1000);
}

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
	driveDistance(40);
}										        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
