#pragma config(Sensor, in1,    potientm,       sensorPotentiometer)
#pragma config(Sensor, in2,    lightsensor,    sensorReflection)
#pragma config(Sensor, in3,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in4,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in5,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, in6,    accel,          sensorAccelerometer)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  sonarCM,        sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  armDown,        sensorTouch)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           armGrab,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Verkefni 2 - part 1 -                                    *|
|*                                      															  *|
|*			Using time, tells the robot to move forward 0.5m and then reverse the 		  *|
|*			same length, then increament by 0.5m until 2.5m.										  *|
|*																		                              *|
\*-----------------------------------------------------------------------------------------------4246-*/
#include "../robheaders/const.h"
#include "../robfuncs/funcs.c"


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
    wait10Msec(1000);
    while (true)
    {
        if (vexRT[STOPBUTTON])
        {
            stopAll();
            break;
        }
        if (lineUnder(0))
        {
            setMotors(75, 0);
        }
        if (lineUnder(1))
        {
            setMotors(55, 55);
        }
        if (lineUnder(2))
        {
            setMotors(0, 75);
        }
    }
}								        // Program ends, and the robot stops
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++